/*게시글 리스트 가져오기*/
export const GET_BOARD_LIST = 'GET_BOARD_LIST';
export const GET_BOARD_LIST_REQUEST = 'GET_BOARD_LIST_REQUEST';
export const GET_BOARD_LIST_SUCCESS = 'GET_BOARD_LIST_SUCCESS';
export const GET_BOARD_LIST_FAILURE = 'GET_BOARD_LIST_FAILURE';

/*게시글 삭제*/
export const DELETE_BOARD = 'DELETE_BOARD';
export const DELETE_BOARD_REQUEST = 'DELETE_BOARD_REQUEST';
export const DELETE_BOARD_SUCCESS = 'DELETE_BOARD_SUCCESS';
export const DELETE_BOARD_FAILURE = 'DELETE_BOARD_FAILURE';


/*게시글 상세보기*/
export const READ_BOARD = 'READ_BOARD';
export const READ_BOARD_REQUEST = 'READ_BOARD_REQUEST';
export const READ_BOARD_SUCCESS = 'READ_BOARD_SUCCESS';
export const READ_BOARD_FAILURE = 'READ_BOARD_FAILURE';

/*게시판 카테고리 리스트 가져오기*/
export const GET_BOARD_CATEGORY = 'GET_BOARD_CATEGORY';
export const GET_BOARD_CATEGORY_REQUEST = 'GET_BOARD_CATEGORY_REQUEST';
export const GET_BOARD_CATEGORY_SUCCESS = 'GET_BOARD_CATEGORY_SUCCESS';
export const GET_BOARD_CATEGORY_FAILURE = 'GET_BOARD_CATEGORY_FAILURE';
/*로그인*/
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';


export const GET_TODO = 'DELETE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const READ_TODO = 'READ_TODO';
export const GET_CATEGORY = 'GET_CATEGORY';

export const LOGIN_TODO = 'LOGIN_TODO';
